server:
  port: 8080

spring:
  application:
    name: codearena-backend

  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/codearena?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2
    username: 3Y2KoM7eouQWXFg.root
    password: 9VR1ZlSKXf5FtBml
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  data:
#    redis:
#      host: localhost
#      port: 6379

jwt:
  secret: change-this-secret-in-production-please-make-it-long
  expiration-ms: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html